name: API Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:  # Cho phép chạy thủ công từ giao diện GitHub

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install Newman
        run: npm install -g newman newman-reporter-htmlextra
      
      - name: Create reports directory
        run: mkdir -p reports
      
      - name: Run Add Product API Tests
        run: |
          newman run "sprint5-with-bugs/api-testing/postman/Add Product.postman_collection.json" -d "sprint5-with-bugs/api-testing/postman/AddProduct.csv" --reporters cli,htmlextra --reporter-htmlextra-export reports/add-product-report.html
      
      - name: Run Edit Product API Tests
        run: |
          newman run "sprint5-with-bugs/api-testing/postman/Edit Product.postman_collection.json" -d "sprint5-with-bugs/api-testing/postman/EditProduct.csv" --reporters cli,htmlextra --reporter-htmlextra-export reports/edit-product-report.html
      
      - name: Run Search and Filter API Tests
        run: |
          newman run "sprint5-with-bugs/api-testing/postman/Search and Filter.postman_collection.json" -d "sprint5-with-bugs/api-testing/postman/SearchFilter.csv" --reporters cli,htmlextra --reporter-htmlextra-export reports/search-filter-report.html
      
      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: api-test-reports
          path: reports/
