name: API Tests with Postman CLI
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Set environment variables
        run: |
          echo "SPRINT_FOLDER=sprint5-with-bugs" >> $GITHUB_ENV
          echo "DISABLE_LOGGING=false" >> $GITHUB_ENV

      - name: Verify sprint folder structure
        run: |
          echo "Checking sprint folder structure..."
          ls -la ${SPRINT_FOLDER} || echo "Sprint folder not found"
          ls -la ${SPRINT_FOLDER}/API || echo "API folder not found"
          ls -la ${SPRINT_FOLDER}/UI || echo "UI folder not found"

      # Tạo thư mục storage và bootstrap/cache với quyền truy cập đúng trước khi khởi động Docker
      - name: Prepare Laravel directories
        run: |
          mkdir -p ${SPRINT_FOLDER}/API/storage/logs
          mkdir -p ${SPRINT_FOLDER
